[workspace]
resolver = "2"

members = ["crates/*", "server"]

[workspace.dependencies]
tokio = { version = "1.53", features = ["full"] }

thiserror = "2.0"
anyhow = "1.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

clap = { version = "4.5", features = ["derive"] }
dotenvy = "0.15"

bytes = "1"
